# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170311_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='meta_keywords',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_Keywords',
            field=models.CharField(default='水果', help_text='meta关键词 有利于SEO 用逗号分割', max_length=255, verbose_name='关键词'),
        ),
    ]
